//
// Created by andreas on 2017-03-14.
//

#ifndef PERSISTENT_ACTIONLIB_PERSISTENTACTIONSERVER_H
#define PERSISTENT_ACTIONLIB_PERSISTENTACTIONSERVER_H


class PersistentActionServer
{

};


#endif //PERSISTENT_ACTIONLIB_PERSISTENTACTIONSERVER_H
